### ISSUE TITLE
Feature: Статус сервера Minecraft

### ISSUE THREAD

**Issue by TinyClayMan** [laefad/CivilizationStatistics#6]
Добавить на одну из существующих страниц (или на новую) блок информации о сервере.

Есть два варианта:
* парсить json и строить объект по нему самостоятельно
  * https://mcapi.us/server/status?ip=[server-ip]
* использовать уже сгенерированное изображение
  * https://mcapi.us/server/image?ip=[server-ip]
  * https://mcapi.us/server/image?ip=[server-ip]&theme=dark
  
В json количество информации больше:
* https://mcapi.us/#usage

**Comment by laefad** [comment]
А есть вариант напрямую из веба без посредника запрашивать инфу о сервере?
Может стоит рассмотреть библиотеку, которая запрашивает информацию о сервере напрямую и попробовать имплементировать в вебе? 

Например вот библиотеку [mcutil](https://github.com/mcstatus-io/mcutil), являющуюся ключевой в сервисе [mcstatus.io](https://mcstatus.io).

**Comment by laefad** [comment]
Добавлено в коммите:

https://github.com/laefad/CivilizationStatistics/commit/bba3274087d27bbbffd073d9c3c7fcc95156e7b3
